setTimeout(()=>{
   document.getElementById("display").innerText="10";
   setTimeout(()=>{
    document.getElementById("display").innerText="9";
    setTimeout(()=>{
        document.getElementById("display").innerText="8";
        setTimeout(()=>{
            document.getElementById("display").innerText="7";
            setTimeout(()=>{
                document.getElementById("display").innerText="6";
                setTimeout(()=>{
                    document.getElementById("display").innerText="5";
                    setTimeout(()=>{
                        document.getElementById("display").innerText="4";
                        setTimeout(()=>{
                            document.getElementById("display").innerText="3";
                            setTimeout(()=>{
                                document.getElementById("display").innerText="2";
                                setTimeout(()=>{
                                    document.getElementById("display").innerText="1";
                                    setTimeout(()=>{
                                        document.getElementById("display").innerText="Happy Independence Day 🏳‍🌈";    
                                    },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
   },1000)
},1000)